# Extra Functions On Numpy

In [1]:
import numpy as np

In [1]:
import numpy as np

a = np.random.randint(1, 100, 15)
a

array([ 8,  3, 80, 15, 42, 96, 82, 92, 72, 56, 50, 48,  9, 70,  2])

In [2]:
b = np.random.randint(1, 100, 24).reshape(6,4)
b

array([[ 6, 40, 84, 89],
       [82, 48, 29, 89],
       [90,  7, 44, 92],
       [66, 51, 86, 33],
       [83, 48,  7, 32],
       [63, 44, 65, 82]])

## np.flip

- This reverses the order of array elements along the specified axis, preserving the shape of the array

In [3]:
np.flip(a)

array([ 2, 70,  9, 48, 50, 56, 72, 92, 82, 96, 42, 15, 80,  3,  8])

In [4]:
np.flip(b)

array([[82, 65, 44, 63],
       [32,  7, 48, 83],
       [33, 86, 51, 66],
       [92, 44,  7, 90],
       [89, 29, 48, 82],
       [89, 84, 40,  6]])

## np.put()

- Replaces specific elements of an array with given values of p_array. Array indexed works on flattened array

In [5]:
np.put(a, [0,1], [100, 530]) ## permanently changes the items in the specified position

In [6]:
a

array([100, 530,  80,  15,  42,  96,  82,  92,  72,  56,  50,  48,   9,
        70,   2])

## np.delete

- Returns a new array with the deletion of sub-arrays along with the mentioned axis.

In [7]:
np.delete(a, 0) ## index

array([530,  80,  15,  42,  96,  82,  92,  72,  56,  50,  48,   9,  70,
         2])

In [8]:
np.delete(a,[0, 2, 4])

array([530,  15,  96,  82,  92,  72,  56,  50,  48,   9,  70,   2])

## set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [3]:
m = np.array([1,2,3,4, 5])
n = np.array([6,7,3,4, 5])

In [4]:
np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [5]:
np.intersect1d(m,n)

array([3, 4, 5])

In [6]:
np.setdiff1d(m,n)

array([1, 2])

In [7]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [8]:
np.in1d(m, 1)

array([ True, False, False, False, False])

## np.clip

- function is used to clip (limit) the values in an array

In [12]:
import numpy as np

a = np.random.randint(1, 100, 15)
a

array([81,  2, 48, 47, 40, 65, 31, 39, 19, 90, 14, 92, 48, 25,  5])

In [11]:
b = np.random.randint(1, 100, 24).reshape(6,4)
b

array([[80, 99, 29, 87],
       [10,  6,  3, 70],
       [72, 38, 83, 92],
       [61, 12, 96, 21],
       [ 1, 31, 34,  8],
       [25, 45, 50, 52]])

In [13]:
np.clip(a, a_min=25, a_max=75)

array([75, 25, 48, 47, 40, 65, 31, 39, 25, 75, 25, 75, 48, 25, 25])

 ## np.swapaxes

## np.uniform

## np.count_nonzero

## np.tile
####  https://www.kaggle.com/code/abhayparashar31/best-numpy-functions-for-data-science-50?scriptVersionId=98816580

## np.repeat
#### https://towardsdatascience.com/10-numpy-functions-you-should-know-1dc4863764c5

## np.allclose and equals