**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [45]:
import numpy as np

### Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [46]:
#Code here
v = np.zeros(10)
v[4] = 1

print(v)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [47]:
#Code here

a,b = map(int, input("Enter two input a and b: ").split()) ### one line split

arr = np.random.random((a,b))

avg = np.mean(arr)

# Print results
print("Generated Array:")
print(arr)

print("Average of the array:", avg)

Enter two input a and b:  3 4


Generated Array:
[[0.24472106 0.48862136 0.86713255 0.82632897]
 [0.72685474 0.21193089 0.75446871 0.33743547]
 [0.89222265 0.59571737 0.78655932 0.95728883]]
Average of the array: 0.64077349175286


### Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [48]:
#Code here

a,b = map(int, input("Enter two input a and b: ").split()) ### one line split

arr  = np.ones((a,b))

arr[1:-1, 1:-1]= 0

print(arr)

Enter two input a and b:  4 4


[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


### `Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [49]:
#Code here

np.linspace(0,1,12)[1: -1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

### Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [50]:
#Code here

np.identity((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [51]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

### Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.`

In [52]:
#Code here

np.random.random((5,5)) * 4

array([[0.64120594, 3.46382985, 0.01256691, 1.89019004, 3.25751144],
       [0.57039197, 0.46351039, 2.92006752, 2.393078  , 2.21479533],
       [3.18393978, 0.05039199, 0.79106672, 3.82802959, 0.51999352],
       [2.34908786, 3.58948404, 3.51687309, 0.92191083, 1.30306632],
       [1.86757595, 3.51258013, 2.7015874 , 3.13300411, 2.34020912]])

* np.random.random((5,5)) generates float values in the range [0, 1).
* To obtain values in the range 0 to 4, you must scale and optionally convert them.

### `Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [53]:
import numpy as np

## given point
point = np.array([2,3])

## random integer coordinates (10,2)
coords = np.random.randint(1,101, size=(10,2))

# Compute Euclidean distance and convert to integer
distances = np.linalg.norm(coords - point, axis=1).astype(int)

print("Coordinates:\n", coords)
print("Distances:\n", distances)

Coordinates:
 [[27 54]
 [40 28]
 [47 47]
 [84 99]
 [68 37]
 [43 24]
 [44 38]
 [71 73]
 [43 23]
 [42 60]]
Distances:
 [ 56  45  62 126  74  46  54  98  45  69]


### `Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [54]:
import numpy as np

arr = np.arange(6*7*8).reshape(6,7,8)

np.where(arr == 99)


(array([1]), array([5]), array([3]))

### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [55]:
#Code here

arr = np.array((1, 2, 3, 4, -8, -10))

result = np.flip(arr).astype(float)

result

array([-10.,  -8.,   4.,   3.,   2.,   1.])

### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [56]:
def count_element(array):

    return np.size(array)

count = count_element(np.array([1, 2]))

count

2

In [57]:
b = np.random.randint(1, 100, 24).reshape(6,4)
b


array([[44, 21, 92,  8],
       [10, 38, 94, 46],
       [34, 41, 88, 80],
       [97, 48, 32,  6],
       [26, 52, 76, 37],
       [65, 50, 18, 53]])

In [58]:
count_element(b)

24

### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [59]:
def softmax(x):
    # Check if input is a NumPy array
    if not isinstance(x, np.ndarray):
        raise TypeError("Input must be a NumPy array")
    
    # Check if input is 1D
    if x.ndim != 1:
        raise ValueError("Input must be a 1D NumPy array")
    
    # Numerically stable softmax
    exp_x = np.exp(x - np.max(x))
    return exp_x / np.sum(exp_x)

In [60]:
a = np.array([86.03331084, 37.7285648,  48.64908087, 87.16563062, 38.40852563, 37.20006318])
b = np.array([33.17344305, 45.61961654, 82.05405781, 80.9647098,  68.82830233, 91.52064278])

In [61]:
softmax(a)

array([2.43733248e-01, 2.56112114e-22, 1.41628283e-17, 7.56266752e-01,
       5.05514197e-22, 1.50974911e-22])

In [62]:
softmax(b)

array([4.57181033e-26, 1.16249922e-20, 7.73872594e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01])

### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [63]:
def vertical_stack(*arrays):

    ## at least one array must be provided
    if len(arrays) == 0:
        raise ValueError("At least one NumPy array must be provided")
    
    # Check all inputs are NumPy arrays
    for arr in arrays:
        if not isinstance(arr, np.ndarray):
            raise TypeError("All inputs must be NumPy arrays")
    
    # Perform vertical stacking
    return np.vstack(arrays)

In [64]:
a = np.array([[0, 1, 2, 3, 4],
              [5, 6, 7, 8, 9]])

b = np.array([[1, 1, 1, 1, 1],
              [1, 1, 1, 1, 1]])

print(vertical_stack(a, b))


[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [65]:
c = np.array([[0.10117373, 0.1677244 , 0.73764059, 0.83166097, 0.48985695],
              [0.44581567, 0.13502419, 0.55692335, 0.16479622, 0.61193593]])

print(vertical_stack(a, b, c))


[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]


In [66]:
vertical_stack(a, [1, 2, 3])


TypeError: All inputs must be NumPy arrays

### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [67]:
import numpy as np
from datetime import datetime, timedelta

def date_array(start, end):
    
    # Type check
    if not isinstance(start, str) or not isinstance(end, str):
        raise TypeError("Both start and end must be strings")
    
    # Date format check and conversion
    try:
        start_date = datetime.strptime(start, "%Y-%m-%d")
        end_date = datetime.strptime(end, "%Y-%m-%d")
    except ValueError:
        raise ValueError("Date format must be YYYY-MM-DD")
    
    # Same year check
    if start_date.year != end_date.year:
        raise ValueError("Dates must be from the same year")
    
    # End date must be >= start date
    if end_date < start_date:
        raise ValueError("End date must be after start date")
    
    # Generate dates
    num_days = (end_date - start_date).days + 1
    dates = [
        (start_date + timedelta(days=i)).strftime("%Y-%m-%d")
        for i in range(num_days)
    ]
    
    return np.array(dates)


In [68]:
date_array('2020-09-15', '2020-09-25')


array(['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
       '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
       '2020-09-23', '2020-09-24', '2020-09-25'], dtype='<U10')

In [69]:
date_array('2022-12-01', '2022-12-06')


array(['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04',
       '2022-12-05', '2022-12-06'], dtype='<U10')

### `Q-14:` Subtract the mean of each row from a matrix.

In [70]:
import numpy as np

b = np.random.randint(1, 100, 24).reshape(6, 4)

b


array([[88, 56, 37, 84],
       [26, 31, 44, 33],
       [90, 32, 88, 76],
       [72, 31,  5, 60],
       [59, 16, 82,  5],
       [79, 10,  8, 29]])

In [71]:
mean_row_wise = np.mean(b, axis=1, keepdims=True)

In [72]:
# Subtract row-wise mean
result = b - mean_row_wise

print(result)

[[ 21.75 -10.25 -29.25  17.75]
 [ -7.5   -2.5   10.5   -0.5 ]
 [ 18.5  -39.5   16.5    4.5 ]
 [ 30.   -11.   -37.    18.  ]
 [ 18.5  -24.5   41.5  -35.5 ]
 [ 47.5  -21.5  -23.5   -2.5 ]]


### `Q-15:` Swap column-1 of array with column-2 in the array.

In [73]:
# Example array
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [74]:
## swap column 1 and column 2

a[:, [0, 1]] = a [:, [1, 0]]

print(a)

[[2 1 3]
 [5 4 6]
 [8 7 9]]


In [75]:
a

array([[2, 1, 3],
       [5, 4, 6],
       [8, 7, 9]])

In [76]:
## swap 1 row with 2nd row

a[[0, 1], :] = a [[1, 0], :]

print(a)

[[5 4 6]
 [2 1 3]
 [8 7 9]]


### `Q-16:` Replace odd elements in arrays with -1.

In [82]:
~(a % 2 == 0)

array([[ True, False, False],
       [False,  True,  True],
       [False,  True,  True]])

In [81]:
## using boolean indexing

a[~(a % 2 == 0)] = -1 

a

array([[-1,  4,  6],
       [ 2, -1, -1],
       [ 8, -1, -1]])

### `Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [83]:
import numpy as np

a = np.array([6, 3, 1, 5, 8])
b = np.array([3, 2, 1, 7, 2])

# np.maximum(a, b) compares elements position by position and picks the larger value from each pair
result = np.maximum(a, b)

print(result)


[6 3 1 7 8]


### `Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [84]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[ 675, 6765, 3937, 4846,  603],
       [5004, 4653, 7850, 3742, 2196],
       [2075, 5795, 9088, 4525, 5087],
       [5516,  518, 8449, 4434, 5085],
       [4320, 5812, 9481, 9626, 3832],
       [3691, 8402, 6984, 7539, 3780],
       [4985, 9589, 1898, 1063, 9262],
       [ 823, 3065, 7194, 4551, 9677]])

In [87]:
## fetch alternate columns

alternate_cols = arr1[:, ::2]
alternate_cols

array([[ 675, 3937,  603],
       [5004, 7850, 2196],
       [2075, 9088, 5087],
       [5516, 8449, 5085],
       [4320, 9481, 3832],
       [3691, 6984, 3780],
       [4985, 1898, 9262],
       [ 823, 7194, 9677]])

In [89]:
arr_normalized = (arr1 - arr1.min()) / (arr1.max() - arr1.min())

arr_normalized

array([[0.01714161, 0.68206136, 0.37329403, 0.47254067, 0.00928049],
       [0.48979146, 0.4514685 , 0.80052407, 0.35200349, 0.18320777],
       [0.16999672, 0.5761546 , 0.93569167, 0.43749318, 0.49885359],
       [0.54569276, 0.        , 0.86592423, 0.42755759, 0.49863522],
       [0.41511082, 0.5780107 , 0.97860028, 0.99443171, 0.36182989],
       [0.3464352 , 0.86079266, 0.70597227, 0.7665684 , 0.35615242],
       [0.487717  , 0.99039196, 0.15067147, 0.05950431, 0.95468938],
       [0.03330058, 0.27808713, 0.72890053, 0.44033191, 1.        ]])

### `Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [90]:
import numpy as np

def nth_largest(arr, n):
    # Input checks
    if not isinstance(arr, np.ndarray):
        raise TypeError("First argument must be a NumPy array")
    if arr.ndim != 1:
        raise ValueError("Array must be 1D")
    if not isinstance(n, int):
        raise TypeError("Second argument must be an integer")
    if n < 1 or n > len(arr):
        raise ValueError("n must be between 1 and length of the array")
    
    # Sort array in descending order
    sorted_arr = np.sort(arr)[::-1]
    
    # Return nth largest (1-based indexing)
    return sorted_arr[n-1]


In [91]:
arr = np.array([12, 34, 40, 7, 1, 0])

print(nth_largest(arr, 3))  # Output: 12
print(nth_largest(arr, 1))  # Output: 40


12
40


### `Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [92]:
a = np.array([1,2,3])

## repeat each element 3 times
part1 = np.repeat(a, 3)
print(part1)

## repeat the whole array 3 times
part2 = np.tile(a, 3)
print(part2)

## combine
result = np.concatenate([part1, part2])

print(result)

[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]
[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]
