## What is numpy?


NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.
At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types.


## Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.


- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.


- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python built-in sequences.

- A growing plethora of scientific and mathematical Python based packages are using NUmPY arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.


## Creating Numpy Arrays

In [1]:
# np.array
import numpy as np

a = np.array([1,2,3])

In [2]:
print(type(a))

<class 'numpy.ndarray'>


In [3]:
# 2D and 3D 

b = np.array([[1,2,3], [4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [4]:
c = np.array([[[1,2], [5,6], [7,8]]])
print(c)

[[[1 2]
  [5 6]
  [7 8]]]


In [5]:
# dtype array


# float data ty pe
np.array([1,2,3], dtype=float)

array([1., 2., 3.])

In [6]:
#bool data type
np.array([1,2,3], dtype=bool)

array([ True,  True,  True])

In [7]:
## np.range -> similar to range in python

np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

In [9]:
## np.reshape

np.arange(1,11).reshape(5,2) ## 5 rows 2 columns 

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [10]:
np.arange(1,11).reshape(2,5) 

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [11]:
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [12]:
np.arange(1,13).reshape(5,2)

ValueError: cannot reshape array of size 12 into shape (5,2)

In [13]:
## np.ones and np.zeros

np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
## np.random

np.random.random((3,4))

array([[0.77429553, 0.02270853, 0.22401954, 0.40980995],
       [0.13570005, 0.74913986, 0.24919704, 0.96846763],
       [0.64315545, 0.60998605, 0.02131829, 0.12501263]])

In [16]:
 ## np.linspace
np.linspace(-10, 10, 10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [17]:
  ## np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Array Attributes

In [18]:
a1 = np.arange(10)
a2 = np.arange(12, dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [19]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [20]:
### ndim 

a1.ndim

1

In [21]:
a2.ndim

2

In [22]:
 ## shape

a1.shape

(10,)

In [23]:
a2.shape

(3, 4)

In [24]:
a3.shape

(2, 2, 2)

In [25]:
 ### size

print(a1.size)
print(a2.size)
print(a3.size)

10
12
8


In [26]:
## item size

# a1 has all items in int

a1.itemsize

8

In [27]:
a1 = np.arange(10, dtype = np.int32)

a1.itemsize

4

In [28]:
 ## dtype

print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


## Changing Datatype


In [29]:
 ## astype

a3.dtype

dtype('int64')

In [30]:
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

## array operations

In [31]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12, 24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [32]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [33]:
## scalar operations

# arthemetic
a1* 2
a2+ 2

array([[14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25]])

In [35]:
## realtional

a2 > 15

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [36]:
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

### Vector Operations

In [37]:
 ## arthmetic

a2 

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [38]:
 a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [39]:
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

## Array Functions

In [40]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[38., 41.,  1.],
       [13., 14., 12.],
       [55., 74., 70.]])

In [41]:
## max/min/sum/prod

np.max(a1)

np.float64(74.0)

In [42]:
np.sum(a1)

np.float64(318.0)

In [43]:
np.prod(a1) ## multiply

np.float64(969421252800.0)

In [44]:
## return the minimum element from the first row only

## 0 -> col and 1 --> row 
np.min(a1, axis=  0)

array([13., 14.,  1.])

In [45]:
np.prod(a1, axis=0)

array([27170., 42476.,   840.])

In [46]:
## mean/median/std/var

np.mean(a1, axis=1)

array([26.66666667, 13.        , 66.33333333])

In [47]:
## trignometirc functions

np.sin(a1)

array([[ 0.29636858, -0.15862267,  0.84147098],
       [ 0.42016704,  0.99060736, -0.53657292],
       [-0.99975517, -0.98514626,  0.77389068]])

In [48]:
## dot product

a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [51]:
a3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [54]:
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [55]:
np.log(a1)

array([[3.63758616, 3.71357207, 0.        ],
       [2.56494936, 2.63905733, 2.48490665],
       [4.00733319, 4.30406509, 4.24849524]])

In [56]:
np.exp(a2)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [65]:
### round/floor/ceil

a= np.random.random((2,3)) * 100
a


array([[ 5.7739348 , 82.90511104, 40.91054428],
       [44.99489519, 99.45208671, 96.95906819]])

In [67]:
np.round(a)

array([[ 6., 83., 41.],
       [45., 99., 97.]])

In [68]:
np.floor(a)

array([[ 5., 82., 40.],
       [44., 99., 96.]])

In [69]:
np.ceil(a)

array([[  6.,  83.,  41.],
       [ 45., 100.,  97.]])

In [ ]:
np.add(a1, a2)